
version: '2'

services:
  t9:
    image: t9:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 server
